name: sigma_task
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  lottie: ^2.7.0
  flutter_bloc: ^8.1.3
  dio: ^5.3.3
  flutter_offline: ^2.1.0
  http: ^1.1.0
  mockito: ^5.4.4
  bloc_test: ^9.1.5
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.3.7
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.jpg"
  min_sdk_android: 21
flutter_native_splash:
  color: "#ffffff"


flutter:

  uses-material-design: true

  assets:
   - assets/images/
   - assets/animes/